

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// // import "../styles/globals.css"; // Your custom styles if any


// // import "bootstrap/dist/css/bootstrap.min.css";
// import "bootstrap/dist/css/bootstrap.min.css";
// import BootstrapClient from "@/components/BootstrapClient";
// import Header from "@/components/Header";
// // import Footer from "@/components/Footer";
// import FooterSection from "@/components/FooterSection";
// import WhatsAppFloat from "@/components/WhatsAppFloat";





// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

// export const metadata: Metadata = {
//     title: "Swarn Sathi",
//     description:
//         "Get quick and easy loans against your goldGenerated by create next app",
//     icons: {
//         icon: "fav.png",
//     },
// };

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {

    
//     return (
//         <html lang="en">
//             <head>
//                 <link
//                     href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;800&display=swap"
//                     rel="stylesheet"
//                 ></link>
//             </head>
//             <body
//                 className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//             >
//                 <BootstrapClient />
//                 <Header />
//                 <div className="m-0 p-0">{children}</div>
//                 <FooterSection />
//                 <WhatsAppFloat />
//             </body>
//         </html>
//     );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "@/components/BootstrapClient";
import Header from "@/components/Header";
import FooterSection from "@/components/FooterSection";
import WhatsAppFloat from "@/components/WhatsAppFloat";
import { PreloaderProvider } from "@/context/PreloaderContext"; // Import the PreloaderProvider

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Swarn Sathi",
    description:
        "Get quick and easy loans against your goldGenerated by create next app",
    icons: {
        icon: "fav.png",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;800&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <PreloaderProvider>
                    {" "}
                    {/* Wrap the entire app inside PreloaderProvider */}
                    <BootstrapClient />
                    <Header />
                    <div className="m-0 p-0">{children}</div>
                    <FooterSection />
                    <WhatsAppFloat />
                </PreloaderProvider>
            </body>
        </html>
    );
}

